# Windows Agent Collector Configuration Example
# This file demonstrates the correct YAML structure for configuration

# Push Gateway Configuration
push:
  gateway-url: "http://pushgateway.example.com:9091"
  username: "monitoring_user" 
  password: "secret_password"
  interval: "30s"
  job-name: "windows_agent"

# Agent Configuration
agent-id: "agent_001"

# Collectors Configuration
collectors:
  enabled: "cpu,memory,net,pagefile"

# Logging Configuration
log:
  level: "info"
  format: "text"

# Process Configuration
process:
  priority: "normal"
  memory-limit: "0"

# Example with environment variables
# push:
#   gateway-url: "${PUSH_GATEWAY_URL}"
#   username: "${PUSH_GATEWAY_USERNAME}"
#   password: "${PUSH_GATEWAY_PASSWORD}"
#   interval: "30s"
#   job-name: "windows_agent"
# 
# agent-id: "${AGENT_ID}"